services:
  start-coding-for-teens:
    build: .
    container_name: start-coding-for-teens
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - start-coding-for-teens
